version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - '80:80'
        links:
            - php

        volumes:
            - ./..:/code
            - ./nginx.conf.d/backend.local.conf:/etc/nginx/conf.d/default.conf

    php:
        build: 'php'
        volumes:
            - ./..:/code
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"

    db:
        image: postgres:14.1-alpine
        hostname: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    db:
        driver: local
